---
language: node_js
sudo: false
node_js:
  - "0.12"
  - "0.11"
  - "iojs"

env:
  - TEST_DIR=packages/storefront
  - TEST_DIR=packages/core
  - TEST_DIR=packages/checkouts
  - TEST_DIR=packages/auth

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/"
    on_success: always
    on_failure: always
    on_start: false

before_install:
  - ./bootstrap.rb
  - cd $TEST_DIR

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember test
