---
language: node_js
sudo: false
node_js:
  - "0.11"
  - "0.10"

env:
  - TEST_DIR=frontend
  - TEST_DIR=core

before_install:
  - cd $TEST_DIR

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember test